--대소문자 구별하지 않음(단, 비밀번호는 구별함)
--CREATE : 생성 / ALTER : 수정 / DROP : 삭제, DELETE : 삭제
--
--오라클 버전이 변경되면서 사용자 생성 시 C## 문자를 넣어서 만들도록 변경 됨
--JAVADB를 만들 때 => C##JAVADB 이런 방식을 C## 사용하지 않겠음
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--USER 생성 (공간할당 - TABLESPACE ~)
--USER 생성은 SYS, SYSTEM 만 가능
--CREATE USER 사용자이름 IDENTIFIED BY 비밀번호
CREATE USER JAVADB IDENTIFIED BY 1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

--GRANT : 권한 부여(사용자 생성만 해서는 아무것도 할 수 없음)
GRANT CONNECT, RESOURCE TO JAVADB;


CREATE USER SCOTT IDENTIFIED BY TIGER
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- SCOTT 에게 부여된 권한
GRANT CONNECT, RESOURCE TO SCOTT;
-- 뷰 생성 권한 부여
GRANT CREATE VIEW TO SCOTT;
-- SYNONYM 생성 권한 부여
GRANT CREATE SYNONYM TO SCOTT;
GRANT CREATE PUBLIC SYNONYM TO SCOTT;


select * from all_users;

GRANT UNLIMITED TABLESPACE TO SCOTT;



GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO SCOTT IDENTIFIED BY TIGER;

ALTER USER SCOTT DEFAULT TABLESPACE USERS;
ALTER USER SCOTT TEMPORARY TABLESPACE TEMP;

-- TEST 사용자 생성 / 비밀번호 1234
CREATE USER test IDENTIFIED BY 1234;

-- 권한 권리

-- 1) 시스템 권한
--    사용자 생성(CREATE USER) / 수정(ALTER USER) / 삭제(DROP USER)
--    데이터베이스 접근((CREATE SESSION) / 수정 (ALTER SESSION))
--    여러 객체 생성(View, Synonym) 및 관리 권한

-- 2) 객체 권한
--    테이블 수정, 삭제, 인덱스 생성, 삽입, 참조, 조회, 수정
--    뷰 삭제, 삽입, 생성, 조회, 수정
--    시퀀스 수정, 조회
--    프로시저, 함수, 패키지 권한

-- 권한 부여
-- CREATE SESSION 을 TEST에게 부여
GRANT CREATE SESSION TO TEST;
GRANT RESOURCE, CREATE TABLE TO test;

-- 테이블 스페이스 USERS에 대한 권한이 없습니다
ALTER USER test DEFAULT TABLESPACE USERS;
ALTER USER test TEMPORARY TABLESPACE TEMP;
ALTER USER test QUOTA 2M ON USERS; -- USERS 에 공간 설정

-- SCOTT 에게 TEST가 생성한 member 테이블 조회 권한 부여
--GRANT SELECT ON member TO SCOTT;

-- 권한 취소
--REVOKE SELECT, INSERT ON member FROM SCOTT;

-- 롤 : 여러 권한들의 모임
-- CONNECT 롤 : CREATE SESSION
-- RESOURCE 롤 : CREATE TRIGGER, CREATE SEQUENCE, CREATE PROCEDURE, CREAATE TABLE




-- 사용자 삭제
DROP USER TEST;
DROP USER TEST CASCADE; -- TEST와 관련된 모든 객체 같이 삭제

-- 사용자 생성 + 테이블 스페이스 권한 부여
CREATE USER TEST2 IDENTIFIED BY 1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
-- 권한부여
GRANT CONNECT, RESOURCE TO test2;


ALTER USER javadb QUOTA 2M ON USERS;

